### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by althonos** [ISA-tools/mzml2isa#1]
Hi @Tomnl,
concerning the ownership of the repository I think the following has to be made:
- pull my master branch in the master branch of your repository
- delete the ISA-Tools/mzml2isa repository
- go to your repo settings and transfer ownership to ISA-Tools
  this way ISA-Tools will have the source repository (and will be the one referenced in web searches)

I'll then perform any development on an **experimental** branch of ISA-Tools/mzml2isa.

I don't think the issues currently on my repository will be ported however, so before deleting my fork I'll first manually transfer all issues to the new ISA-Tools/mzml2isa repository.

Are you okay with that ?

(cced: @rsalek, @proccaserra, @agbeltran, @djcomlab)

**Comment by Tomnl** [comment]
Sounds like a good idea to me. I didn't realise you could transfer ownership. 

I will pull your master branch into the master branch for my repo now.

**Comment by Tomnl** [comment]
Ok, my repo is now up to date with the @althonos master branch. 

Please could someone from the ISA-tab team team (@proccaserra, @agbeltran, @djcomlab) delete ISA-tools/mzml2isa repo?

I will then transfer ownership of this repo.

**Comment by djcomlab** [comment]
Hi, this is done just now, @Tomnl please go ahead and transfer ownership. Thanks!

**Comment by Tomnl** [comment]
Thanks @djcomlab,

Slight problem though. I need admin rights for the ISA-tools to transfer the repo.

Would it be possible to get admin rights for the organization?

If this is a problem, I could email github and they might be able to provide a workaround.

**Comment by djcomlab** [comment]
Hi Tom, shouldn't be a problem, I'll temporarily grant you full admin
rights for the org to do this.

**Comment by Tomnl** [comment]
Great. Ownership now transferred.
