### ISSUE TITLE
[imzml] KeyError: 'Spectrum Representation'

### ISSUE THREAD

**Issue by lomereiter** [ISA-tools/mzml2isa#21]
Lots of imzML files we have don't contain this field _in the top-level `fileContent` node_. There are similar entries in IMS ontology that seem to be used more often: IMS:1000030/IMS:1000031

(_updated_ the description)

**Comment by rsalek** [comment]
Thanks, Artem

@althonos @Tomnl was this to keep the compatibility to mzML2ISA?

http://www.rubydoc.info/search/gems/imzml/0.1.4?q=Spectrum
http://www.rubydoc.info/gems/imzml/0.1.4/ImzML/OBO/IMS

**Comment by proccaserra** [comment]
Any plans for making the vocabulary available from OLS or other ontology server?
I could only find it from the following  link:
https://ms-imaging.org/wp/wp-content/uploads/2016/09/imagingMS.zip
thx

**Comment by Tomnl** [comment]
Thanks @lomereiter, 

Is it possible to provide a link to an example imzML file where this has occurred?

**Comment by lomereiter** [comment]
Some observations on files produced by different converters:
* Xcalibur → TMC (standard Thermo software) reports both spectrum representation (profile/centroided) and IBD binary type (continuous/processed) in `fileContent`
* SCiLS Lab (standard Bruker software) reports IBD binary type in `fileContent` and spectrum representation in the `referenceableParamGroup` with id "spectrum"
* Xcalibur → ProteoWizard → imzmlConverter reports IBD binary type in `fileContent` and spectrum representation in each `spectrum` separately

In practice, continuous is pretty much equivalent to profile (because spectra share the same m/z axis) and processed to centroided, but these are different concepts nevertheless.

Attached are examples for the last two conversion scenarios.

[example_scils_imzml.zip](https://github.com/ISA-tools/mzml2isa/files/780184/example_scils_imzml.zip)
[example_xcalibur_pwiz_imzmlconverter.zip](https://github.com/ISA-tools/mzml2isa/files/780262/example_xcalibur_pwiz_imzmlconverter.zip)

**Comment by Tomnl** [comment]
Thanks for the useful information @lomereiter, 

 At the moment we have been relying on the "Spectrum representation" being in the [file content](http://www.peptideatlas.org/tmp/mzML1.1.0.html#filecontent) section of the mzML or imzML file. 

However, it seems quite often the "spectrum representation" is not recorded here. This actually seems to match up with the mzML schema, where the "spectrum representation" **MAY** be found in the <fileContent> section but **MUST** be found in the  [spectrum](http://www.peptideatlas.org/tmp/mzML1.1.0.html#spectrum)  section. See cvParam Mapping Rules.

I will look into this

**Comment by Tomnl** [comment]
Hi @lomereiter, if you could test you get the expected results using this [ branch. ](https://github.com/ISA-tools/mzml2isa/tree/profile_centroid_fix)

**Comment by Tomnl** [comment]
Hi all, 

I will close this issue today unless anybody has any objections
