### ISSUE TITLE
Consider using -o OUT_PATH as-is

### ISSUE THREAD

**Issue by sneumann** [ISA-tools/mzml2isa#24]
Hi, if I run `mzml2isa -i IN_PATH -o OUT_PATH -s STUDY_ID` ,
the output is placed into `OUT_PATH/STUDY_ID`.
If I am on the commandline, I can happily run 
`mzml2isa -i IN_PATH -o OUT_PATH/STUDY_ID -s STUDY_ID`,
i.e. I would prefer if OUT_PATH is under my full control. 
Yours, Steffen

**Comment by Tomnl** [comment]
Hi @sneumann, thanks for your comment.

This seems sensible and won't require many changes. I will look into it next week.

**Comment by althonos** [comment]
I guess it could be feasible to use a `-O` flag to keep a backwards compatible API :)

**Comment by Tomnl** [comment]
Updated and merged #26 . Let me know if there is any problems with the new code.

I will close the issue if I don't hear anything back.
