### ISSUE TITLE
No license available

### ISSUE THREAD

**Issue by pcm32** [ISA-tools/mzml2isa#32]
Hi guys!

Thanks for the great work! Do you think it might be possible to add a license to this repo? Thanks!

Pablo

**Comment by althonos** [comment]
@tomnl started this project as GPLv3, and I went with it. I'll add an actual license file.

**Comment by Tomnl** [comment]
Happy to use another license if anybody has a preference

**Comment by althonos** [comment]
GPLv3 license available as `COPYING` in the repository.
